spring:
  application:
    name: jordanApp
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: Jordan
    password: jordan
    driver-class-name: oracle.jdbc.OracleDriver
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8801/eureka/
    fetchRegistry: true

feign:
  target:
    admin: sx2-server-auth-admin
    cipher: sx2-server-cipher
  client:
    config:
      default:
        connectTimeout: 60000
        readTimeout: 10000